### ISSUE TITLE
如何解决与JXSegmentedView混合使用手势冲突的问题？

### ISSUE THREAD

**Issue by greezi** [l1Dan/NXNavigationExtension#10]
## 问题描述

感谢提供这么好用的库，在使用过程中遇到了一个问题，开启手势返回后，在JXSegmentedView的页面会出现无法返回的情况。开启
`nx_enableFullScreenInteractivePopGesture`也无法返回

**Comment by greezi** [comment]
Demo:
[gesturesTest.zip](https://github.com/l1Dan/NXNavigationExtension/files/8312959/gesturesTest.zip)

**Comment by l1Dan** [comment]
感谢反馈
之前我下载 JXSegmentedView 里面的示例代码看了问题所在，应该是手势冲突了。你可以试着使用手势滑动下“导航栏”区域应该是可以滑动返回的。
另外我看下怎么帮你处理下手势冲突的问题。

**Comment by l1Dan** [comment]
[gesturesTest_v1.zip](https://github.com/l1Dan/NXNavigationExtension/files/8313162/gesturesTest_v1.zip)

上面的代码已经把手势问题解决了哈，可以看下。
如果还有手势冲突的问题可以参考[如何解决 UIScrollView 和 UIPageViewController 全屏手势冲突?](https://github.com/l1Dan/NXNavigationExtension/#-faq-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by greezi** [comment]
感谢耐心解答。目前侧滑手势可以了，但全屏的侧滑手势还是没反应，请教下大佬应该如何解决呢

**Comment by l1Dan** [comment]
全屏手势也是一样的逻辑
```swift
navigationController.map {
    segmentedView.contentScrollView?.panGestureRecognizer.require(toFail: $0.nx_fullScreenPopGestureRecognizer)
}
```

**Comment by greezi** [comment]
好的。感谢~么么么么么么么么么哒

**Comment by l1Dan** [comment]
不客气。没关系问题的话，可以先把 issue 关闭了哈。

**Comment by l1Dan** [comment]
不客气。没关系问题的话，我先把 issue 关闭了哈。
