### ISSUE TITLE
在Swiftui中隐藏导航栏

### ISSUE THREAD

**Issue by qingweiSun** [l1Dan/NXNavigationExtension#12]
## 发生什么问题？
  在Swiftui中将导航栏设为透明，但是布局依然留出了导航栏的间距
```
  configuration.navigationBarAppearance.backgroundColor = .clear
  configuration.navigationBarAppearance.shadowColor = .clear
```
## 期望如何改进此问题？
隐藏这块留白
## Demo 中是否出现这个问题？

无此场景

## 额外信息（可选）

**NXNavigationExtension 版本：**
4.1.1
**Xcode 版本：**
Version 13.4.1 (13F100)
**运行平台：**
ios模拟器
**截图、示例代码等：**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/16513906/178187508-07af05ed-87b6-46c1-a6f3-95ce113f3543.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/16513906/178187845-388a7419-8957-4a72-afa5-85b87b8faaf6.png">

**Comment by qingweiSun** [comment]
```
.navigationBarHidden(true) 
```
可以解决，但这样，从有导航栏跳转到无就感觉有点怪

**Comment by l1Dan** [comment]
你试下 `.edgesIgnoringSafeArea(.top)` 这种方式。

**Comment by qingweiSun** [comment]
感谢，可以
