### ISSUE TITLE
pod 'NXNavigationExtension/SwiftUI'报错

### ISSUE THREAD

**Issue by SunBoyXiao** [l1Dan/NXNavigationExtension#13]
使用pod安装swift版本报错，xocde是最新版本、pod是最新版本、项目最低值iOS10
[!] CocoaPods could not find compatible versions for pod "NXNavigationExtension/SwiftUI":
  In Podfile:
    NXNavigationExtension/SwiftUI

Specs satisfying the `NXNavigationExtension/SwiftUI` dependency were found, but they required a higher minimum deployment target.

请问大神怎么解决？我看文档上4.x版本的最低支持是iOS9.0。

**Comment by l1Dan** [comment]
是不是没有更新 CocoaPods repo。
