### ISSUE TITLE
关于 NXNavigationBar 导航栏返回按钮问题

### ISSUE THREAD

**Issue by wtdu** [l1Dan/NXNavigationExtension#16]
在导航栏的topViewController 中，调用 .pushViewController(VC1, animated: true) 进入 一个新的控制器(假设VC1)，如果在此同时将导航栏的ViewControllers数组手动改变（移除一个控制器），会出现一个奇怪的现象，在push之后的VC1 页面，自定义的返回按钮 navigationItem.leftBarButtonItem 未正常显示出来，在此同时会显示一个应该是NXNavgationExtension 内部实现的一个返回按钮，并且我在VC1中实现nx_useSystemBackButton = false 的逻辑，也无法解决这个问题。

这里有一段伪代码：
let topViewController = navController.topViewController
let vc1 = ViewController()
topViewController.navigationController?.pushViewController(vc1, animated: true)
// 这里是将当前控制器移除
topViewController.navigationController?.viewControllers.remove(topViewController)
⭐️：这样做的目的是，在返回的时候，不显示上一个控制器

**Comment by l1Dan** [comment]
可以提供一个demo吗？我调试下看看👀

**Comment by wtdu** [comment]
可以，晚点我上传一个

**Comment by l1Dan** [comment]
你这里实际是把 rootViewController 移除了，也就是说 VC1 成为了新的 rootViewController，自然就不显示“返回按钮”了，这种现象属于正常情况。

**Comment by l1Dan** [comment]
@wtdu  已经提交修复代码，可以试下看有没有问题。

`pod 'NXNavigationExtension', :git => 'https://github.com/l1Dan/NXNavigationExtension.git', :commit => '1f76051'`

----
没有问题我就发布新的版本😋

**Comment by wtdu** [comment]
@l1Dan 试了一下，没问题，确认已修复👍🏻

**Comment by l1Dan** [comment]
发布 [4.1.6](https://github.com/l1Dan/NXNavigationExtension/tree/4.1.6)

**Comment by wtdu** [comment]
从 导航栏的根视图页面Push 到一个新页面，一般什么情况下自定义返回按钮leftBarButtonItem 会被系统的backBarButtonItem 强制覆盖？内部实现的机制是什么？

**Comment by wtdu** [comment]
你好，使用最新版本，我这边遇到个新问题，我从导航栏的以及页面push到二级页面，如果二级页面 设置导航栏背景色为透明，且考虑自定导航栏，系统的backBarButonItem 本应该不显示，但现在却显示出来，无法正常隐藏，我在sdk的demo中尝试没有这种情况，项目中遇到了这个问题，这种问题一般是什么情况导致的，是我在什么地方使用不当导致的吗？

**Comment by l1Dan** [comment]
系统返回按钮默认是不显示的。
区分是否为系统返回按钮，长按返回按钮如果出现3d touch 操作就是系统按钮，反之则不是。另外你截图看下，或者贴下代码看下😀

**Comment by wtdu** [comment]
![IMG_0318](https://user-images.githubusercontent.com/42770407/234772919-feea95e1-4a71-409e-8095-72a9ca17c63b.jpg)

**Comment by l1Dan** [comment]
带横杆箭头的返回按钮是你自定义的吗？也就是说你不需要框架提供的返回按钮是吧

**Comment by wtdu** [comment]
> <img alt="image" width="330" src="https://user-images.githubusercontent.com/7961100/234778984-a62b226a-684d-4915-b6f4-b6d0d42419e2.png">
> 
> 带横杆箭头的返回按钮是你自定义的吗？没设置导航栏背景色的时候，这个返回箭头是不是被挡住了。会不会跟“等级”、“勋章”一样，这个返回箭头也是开发人员自己添加的呢？
> 
> 另外 `nx_useSystemBackButton` 默认就是 `false`，直接设置为 `false` 的话不会有其他效果，在这里可以去掉。需要使用系统的返回按钮时才需要设置为 `true`，不需要系统返回按钮不设置即可。框架默认使用 `leftBarButtonItem` 作为返回按钮。
> 
> 如果需要去掉框架自带的返回按钮，使用自定义返回按钮也可以这么做：
> 
> 1. 使用 leftBarButtonItem 覆盖框架提供的返回按钮
>    `navigationItem.leftBarButtonItem = UIBarButtonItem(image: "Back.png", style: .plain, target: <#T##Any?#>, action: <#T##Selector?#>)`
> 2. 导航栏透明（模拟导航栏隐藏的效果，可以让导航栏所在区域底部视图接收到事件）
>    `override var nx_translucentNavigationBar: Bool { return true }`

对红框这个是我自定义的，且非leftBarButonItem 而是基于view 上的一个UIbutton，因为这个页面的导航栏是自定义（UIView）

**Comment by wtdu** [comment]
找到原因了 
加了这句代码就可以
override var nx_translucentNavigationBar: Bool { return true }

**Comment by l1Dan** [comment]
> 找到原因了 
> 
> 加了这句代码就可以
> 
> override var nx_translucentNavigationBar: Bool { return true }

好的。你这种场景更适合“导航栏”透明，导航栏“背景”透明的话，导航栏底部区域还无法点击。

**Comment by wtdu** [comment]
> > 找到原因了
> > 加了这句代码就可以
> > override var nx_translucentNavigationBar: Bool { return true }
> 
> 好的。你这种场景更适合“导航栏”透明，导航栏“背景”透明的话，导航栏底部区域还无法点击。

对对对，之前没考虑到，细看了源码和demo，确实这样，感谢
