### ISSUE TITLE
建议WKWebView增加全屏侧滑

### ISSUE THREAD

**Issue by kinmoLun** [l1Dan/NXNavigationExtension#2]
如题

**Comment by l1Dan** [comment]
WKWebView 的全屏滑动返回需要需要而外的添加，现在就已经支持了哈。代码如下：

```swift
extension YourViewController {
    override var nx_enableFullScreenInteractivePopGesture: Bool {
        return true
    }
}
```

另外 WKWebVIew 还支持页面内手势滑动返回，代码如下：
```swift
webView.allowsBackForwardNavigationGestures = true
webView.gestureRecognizers?.last?.isEnabled = false
```

UIScrollView & UIPageViewController 解决手势冲突方案 [README](https://github.com/l1Dan/NXNavigationExtension/blob/main/README.md) 里面也有说明。

**Comment by l1Dan** [comment]
> 如题

WKWebView 的全屏滑动返回需要需要而外的添加，现在就已经支持了哈。代码如下：

```swift
extension YourViewController {
    override var nx_enableFullScreenInteractivePopGesture: Bool {
        return true
    }
}
```

另外 WKWebVIew 还支持页面内手势滑动返回，代码如下：
```swift
webView.allowsBackForwardNavigationGestures = true
webView.gestureRecognizers?.last?.isEnabled = false
```

UIScrollView & UIPageViewController 解决手势冲突方案 [README](https://github.com/l1Dan/NXNavigationExtension/blob/main/README.md) 里面也有说明。
