### ISSUE TITLE
xcode 15 运行ios17设备程序闪退

### ISSUE THREAD

**Issue by Jsh505** [l1Dan/NXNavigationExtension#22]
运行报错 Thread 1: "A trait environment returned a trait collection with unspecified values for traits that are not allowed to be unspecified. This is a serious application bug and will cause undefined behavior. This issue may be caused by your class overriding the traitCollection property getter, which is not supported. Make sure to use the appropriate API if you are trying to override traits. Trait Environment: <UITabBarSwappableImageView: 0x116794170; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; tintColor = UIExtendedGrayColorSpace 0.572549 0.85; image = <UIImage:0x6000030173c0 CGImage anonymous; (24 24)@3>; layer = <CALayer: 0x60000031b0c0>>; Trait Collection: <UITraitCollection: 0x11645fb60; HorizontalSizeClass = Compact, PreferredContentSizeCategory = L>"

**Comment by l1Dan** [comment]
感谢反馈，我看下

**Comment by l1Dan** [comment]
> 运行报错 Thread 1: "A trait environment returned a trait collection with unspecified values for traits that are not allowed to be unspecified. This is a serious application bug and will cause undefined behavior. This issue may be caused by your class overriding the traitCollection property getter, which is not supported. Make sure to use the appropriate API if you are trying to override traits. Trait Environment: <UITabBarSwappableImageView: 0x116794170; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; tintColor = UIExtendedGrayColorSpace 0.572549 0.85; image = <UIImage:0x6000030173c0 CGImage anonymous; (24 24)@3>; layer = <CALayer: 0x60000031b0c0>>; Trait Collection: <UITraitCollection: 0x11645fb60; HorizontalSizeClass = Compact, PreferredContentSizeCategory = L>"

意思是说有地方重写 `traitCollection ` 的 Setter 方法了，但是这个框架里面并没有重写的地方，可以看下你们项目里有没有地方重写，第三方库的也要拍查下。提示里面出现 `UITabBarSwappableImageView ` ，可能跟 TabBar 相关。

另外我跑了一下 Xcode15 和 iOS17，目前还没有看到问题，如果有问题的话，可以在地下留言，我会看到的哈。
