### ISSUE TITLE
在iOS16上，使用 NavigationStack ，不同的界面导航栏颜色会有bug

### ISSUE THREAD

**Issue by Monkey-X-Byte** [l1Dan/NXNavigationExtension#23]
## 发生什么问题？

ℹ 替换这一行用于描述发生什么问题。

## 期望如何改进此问题？

ℹ 替换这一行用于描述如何改进此问题。

## Demo 中是否出现这个问题？

ℹ 替换这一行用于回答“是”或“否”。

## 额外信息（可选）

**NXNavigationExtension 版本：**
**Xcode 版本：**
**运行平台：**
**截图、示例代码等：**

**Comment by l1Dan** [comment]
你看下示例代码有没有问题，我这边没有出现。或者你吧你的 demo 代码发下，我看看

**Comment by Monkey-X-Byte** [comment]
1、注册：
 var classes: [AnyClass] = []
        if #available(iOS 15.0, *) {
            classes = [
                NSClassFromString("SwiftUI.SplitViewNavigationController"),
                NSClassFromString("SwiftUI.UIKitNavigationController"),
            ].compactMap { $0 }
        } else {
            classes = [
                NSClassFromString("SwiftUI.SplitViewNavigationController"), // iOS14
            ].compactMap { $0 }
        }

    //全局修改
        let defaultConfiguration = NXNavigationConfiguration.default
        defaultConfiguration.navigationBarAppearance.backgroundColor = .white //背景色
        defaultConfiguration.navigationBarAppearance.tintColor = .black //返回按钮箭头颜色
        defaultConfiguration.registerNavigationControllerClasses(classes) { navigationController, configuration in
            // Configure
            navigationController.nx_applyFilterNavigationVirtualWrapperViewRuleCallback(NXNavigationVirtualView.configureWithDefaultRule(for:))
            return configuration
        }
        
 2、APage
configuration.navigationBarAppearance.backgroundColor = .clear //背景色

3、BPage
configuration.navigationBarAppearance.backgroundColor = .white //背景色

APage Push 到 BPage，之后返回，APage 导航栏颜色变为白色了

**Comment by l1Dan** [comment]
> 1、注册： var classes: [AnyClass] = [] if #available(iOS 15.0, *) { classes = [ NSClassFromString("SwiftUI.SplitViewNavigationController"), NSClassFromString("SwiftUI.UIKitNavigationController"), ].compactMap { $0 } } else { classes = [ NSClassFromString("SwiftUI.SplitViewNavigationController"), // iOS14 ].compactMap { $0 } }
> 
> ```
> //全局修改
>     let defaultConfiguration = NXNavigationConfiguration.default
>     defaultConfiguration.navigationBarAppearance.backgroundColor = .white //背景色
>     defaultConfiguration.navigationBarAppearance.tintColor = .black //返回按钮箭头颜色
>     defaultConfiguration.registerNavigationControllerClasses(classes) { navigationController, configuration in
>         // Configure
>         navigationController.nx_applyFilterNavigationVirtualWrapperViewRuleCallback(NXNavigationVirtualView.configureWithDefaultRule(for:))
>         return configuration
>     }
> ```
> 
> 2、APage configuration.navigationBarAppearance.backgroundColor = .clear //背景色
> 
> 3、BPage configuration.navigationBarAppearance.backgroundColor = .white //背景色
> 
> APage Push 到 BPage，之后返回，APage 导航栏颜色变为白色了

[SwiftUIDemo.zip](https://github.com/l1Dan/NXNavigationExtension/files/13775010/SwiftUIDemo.zip)

4.1.8 发布已经修复，你试下看
