### ISSUE TITLE
启用全屏滑动返回手势后，在局部页面禁用滑动返回手势无效

### ISSUE THREAD

**Issue by kinmoLun** [l1Dan/NXNavigationExtension#6]
如题

**Comment by kinmoLun** [comment]
- (BOOL)nx_checkFullScreenInteractivePopGestureEnabledWithViewController:(__kindof UIViewController *)viewController {
    if (viewController.nx_enableFullScreenInteractivePopGesture) {
        return viewController.nx_enableFullScreenInteractivePopGesture;
    }
    if (self.nx_fullScreenInteractivePopGestureEnabled) {
        return self.nx_fullScreenInteractivePopGestureEnabled;
    }
    return NO;
}

这里应该做一个优先级判断

**Comment by l1Dan** [comment]
4.0.1 版本已经修复，`pod update` 试下看有没有问题哈。

**Comment by l1Dan** [comment]
没什么问题的话先关闭了，有问题再提哈
