### ISSUE TITLE
如何从导航栏底下位置布局

### ISSUE THREAD

**Issue by jianjianhao** [l1Dan/NXNavigationExtension#7]
使用了这个组件，不知道怎么让坐标从导航栏下面开始，CGRectMake(100, 0, 60, 40);

**Comment by l1Dan** [comment]
你指的是 UIViewController 的 View 的坐标从导航栏底部开始布局吗？
`edgesForExtendedLayout = UIRectEdge(rawValue: 0)` 这种方式目前支持还不太友好哦，我[文档](https://github.com/l1Dan/NXNavigationExtension/blob/main/Documentation/NXNavigationExtensionUIKit.md)里面有提到这个问题。

**Comment by jianjianhao** [comment]
这样啊，就是暂时还没好的方法可以从导航栏底部开始布局？

**Comment by l1Dan** [comment]
我这边提交下更新，但是还要全面测试下才会新的发版本。你用 master 最新的代码看下是否符合你的需求。

**Comment by jianjianhao** [comment]
好像没啥问题，不知道会不会影响别人之前用的，我只是刚开始用的，或者我自己改下也行

**Comment by l1Dan** [comment]
你先使用 UIViewController `edgesForExtendedLayout = .all` 的默认方式处理，目前来说这种方式最有效。`edgesForExtendedLayout = UIRectEdge(rawValue: 0)` 这种方式我先测试下兼容性，没啥问题后面我就发个新的版本。

**Comment by l1Dan** [comment]
bf1b89f8f6a5b24931b73e36be8eba3d4d8dc28e 这个提交已经添加对 `edgesForExtendedLayout ` 属性的全面支持。

**Comment by l1Dan** [comment]
已经发布新版本 [4.0.3](https://github.com/l1Dan/NXNavigationExtension/releases/tag/4.0.3)，看下有没有问题哈。这个 issue 我先关闭了，有问题再打开。
