### ISSUE TITLE
可以支持导航栏高度设置吗？

### ISSUE THREAD

**Issue by AlanFeiyang** [l1Dan/NXNavigationExtension#8]
ℹ 如果不通用请说明一定要添加的理由
1. 默认系统NavigationBar高度。
2. 支持动态设置导航栏高度。

**Comment by l1Dan** [comment]
目前没有一键修改导航栏高度的 API。设计逻辑就是跟随系统导航栏的变化（包括frame、hidden，position），加入类似一键修改导航栏高度的 API 复杂度会提升，但是你可以参考下示例代码的自定义导航栏部分，应该可以满足你的需求😁
