### ISSUE TITLE
关于nx_navigationBarBackgroundImage、nx_navigationBarBackgroundColor

### ISSUE THREAD

**Issue by League2EB** [l1Dan/NXNavigationExtension#9]
## 问题描述

问题一：我设定了nx_navigationBarBackgroundImage，但发现图片异常放大，请问我该设定什么来达到正确的大小？亦或是图片尺寸是否有限定？

问题二：我想要在TableView滚动时，替换导航栏颜色，除了自行计算contentOffset之外，我该怎么调用NXNavigationExtension来设定我要改变的颜色？

谢谢您！

**Comment by l1Dan** [comment]
问题一：通过 `nx_navigationBarBackgroundImage` 属性设置背景图片时发现 contentMode 不对可以使用 `nx_navigationBar.backgroundImageView.contentMode` 来修改【内部使用 `UIViewContentModeScaleAspectFill` 模式】，如果还无法满足设置导航栏背景图片的需求，也可以使用自定义导航栏来解决问题 [代码参考](https://github.com/l1Dan/NXNavigationExtension/blob/main/Examples/Shared/UIKit/Advanced/ViewController04_CustomNavigationBar.swift)。

问题二：动态设置 `nx_navigationBarBackgroundColor` 时需要配合 `nx_setNeedsNavigationBarAppearanceUpdate()` 方法调用 [代码参考](https://github.com/l1Dan/NXNavigationExtension/blob/main/Examples/Shared/UIKit/Advanced/ViewController09_ScrollChangeNavigationBar.swift)。
